FROM php:8.4-fpm

# 1. Install dependencies
RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev libxml2-dev zip unzip libpq-dev nodejs npm

# 2. Bersihkan cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# 3. Install Ekstensi
RUN docker-php-ext-install pdo_pgsql mbstring exif pcntl bcmath gd

# 4. Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 5. Set working directory
WORKDIR /var/www

# 6. Ubah user ke www-data (ID 1000) agar tidak error permission di Linux/WSL
RUN usermod -u 1000 www-data

EXPOSE 9000
CMD ["php-fpm"]